config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

    root 'sessions#new_session_user'
    get '/availabilities' => 'availabilities#index'

  get '/new_company' => 'sessions#new_company'
  get '/new_session_tailor' => 'sessions#new_session_tailor'
  get '/new_session_user' => 'sessions#new_session_user'

  get 'tailors/edit_tailor' => 'tailors#edit_tailor'

  get 'users/forgot_password'=> 'users#forgot_password'
  post 'users/forgot_password/reset' => 'users#forgot_password_mail'

get '/availabilities/index' => 'availabilities#index'

  post 'appointments/:id' => 'appointments#status'
  post 'tailors/dashboard/data' => 'tailors#dataLog'
  post 'companies/data' => 'companies#dataLog'

  post 'dashboard/appointment_create' => 'users#appointment_booked'

  get '/dashboard' => 'users#dashboard'

  get '/tailors/dashboard'  => 'tailors#dashboard'

  post 'sessions/login_user'
  post 'sessions/login_company'
  post 'sessions/login_tailor'

  post '/tailors/:id/' => 'tailors#destroy'

  delete '/logout' => 'sessions#logout'

  resources :sessions

  resource :companies do
    resources :tailors
    resources :availabilities
  end

  resources :tailors do
    resources :appointments
    resources :availabilities
  end

  resources :users do
    resources :appointments
  end

  resources :appointments do
    resources :articles
  end

  resources :articles

  get '/session' => 'sessions#show'
  get '/login' => 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :appointments
  mount_uploader :image, ImageUploader

  before_save :format_values
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  validates_uniqueness_of :email, :phone
  # validates_format_of :phone, :with => /\A(1?(?: |\-|\.)?(?:\(\d{3}\)|\d{3})(?: |\-|\.)?\d{3}(?: |\-|\.)?\d{4})\z/, message: "incorrect format, ex. 888-888-8888"
  # validates :zip, format: { with: /(^\d{5}$)|(^\d{5}-\d{4}$)/, message: "Invalid Zipcode" }


  ########## For Faker Gem ONLY  ############
  # validates_uniqueness_of :email, :phone, :first_name, :last_name, :address

  def format_values
    first_name.capitalize!
    last_name.capitalize!
    email.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessor :password, :password_confirmation
    before_action :set_user, only: [:show, :edit, :update, :destroy, :dashboard]
    # before_action :require_logged_in_user, only: [:dashboard]

    def show
      @appointment = Appointment.new
    end

    def new
      @user = User.new
    end

    def index
    end

    def edit
    end

    def dashboard
      @tailors = Tailor.all
      @days = Date.today.all_week
    end

    def method_name

    end

    def create
      @user = User.new user_params
      # before_save do |user|
      #   user.first_name = user.first_name.downcase.capitalize
      #   user.last_name = user.last_name.downcase.capitalize
      #   user.email = user.email.downcase
      # end

      if @user.save
        log_in(@user)
        UserMailer.registration_confirmation(@user).deliver
        redirect_to dashboard_path,notice: "#{@user.first_name} was successfully created"
      else
        render :new
      end
    end

    def update
      if @user.update(user_params)
        redirect_to dashboard_path
      else
         redirect_to dashboard_path
      end
    end

    def appointment_booked
      @user = current_user
      @appointment = current_user.appointments.last
      @tailor = @appointment.tailor
      @appointment.stages = "Appointment Booked"
      @appointment.save
      UserMailer.appointment_booked(@user).deliver
      UserMailer.appointment_bookedT(@tailor).deliver
      redirect_to dashboard_path
    end

    def destroy
      @user.destroy
      redirect_to root_path
    end

    def forgot_password
    end

    def forgot_password_mail
      @user = User.find_by(email: params[:email])
      if @user.nil?
        # Need some logic here
      else
        @user.password = ("#{@user.first_name}Reset")
        @user.password_confirmation = ("#{@user.first_name}Reset")
        if @user.save
          puts "This Saved!!!!!"
          UserMailer.forgot_user_password(@user).deliver
          redirect_to new_session_user_path
        else
          puts "not saved"
        end
      end
    end


    private

    def set_user
      # user_id is stored in the sessions, not params, but until fixed use params.!!!!
      @user = User.find(session[:user_id])
      # @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :address, :phone, :zip, :image, :remote_image_url)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <p>
    Upload your profile picture
  </p>
  <%= f.file_field :image %>
  <%# f.text_field :remote_image_url %>
  <%= f.input :first_name, :placeholder => "First name", label: false %>
  <%= f.input :last_name, :placeholder => "Last name", label: false%>
  <%= f.input :address, :placeholder => "Address", label: false %>
  <%= f.input :zip, :placeholder => "Zipcode", label: false %>
  <%= f.input :phone, :placeholder => "Phone number", label: false %>
  <%= f.input :email, :placeholder => "Email", label: false %>
  <%= f.input :password, :placeholder => "password", label: false %>
  <%= f.input :password_confirmation, :placeholder => "password confirmation", label: false %>
  <%= f.button :submit, value="Create!"  %>
<% end %>

app/views/users/_form2.html.erb
<%= simple_form_for @user do |f| %>
  <p>
    Upload your profile picture
  </p>
  <%= f.file_field :image %>
  <%# f.text_field :remote_image_url %>
  <%= f.input :first_name, :placeholder => "First name", label: false %>
  <%= f.input :last_name, :placeholder => "Last name", label: false%>
  <%= f.input :address, :placeholder => "Address", label: false %>
  <%= f.input :zip, :placeholder => "Zipcode", label: false %>
  <%= f.input :phone, :placeholder => "Phone number", label: false %>
  <%= f.input :email, :placeholder => "Email", label: false %>
  <%= f.input :password, :placeholder => "password", label: false %>
  <%= f.input :password_confirmation, :placeholder => "password confirmation", label: false %>
  <%= f.button :submit, value="Update"  %>
<% end %>

app/views/users/dashboard.html.erb
<div id="userDashContainer">
  <p id="notice"><%= flash[:notice] %></p>
<div class="dBackground">


<div class="Hello">
  Hello <span id="userGreeting"><%= current_user.first_name %></span>
</div>
<div class="imgUser">
  <%= image_tag @user.image_url(:thumb).to_s%>
</div>
</div>

<div class="DashbContent">

  <div class='editbutton'>
    <%= link_to 'Edit Profile', edit_user_path(current_user)%>
  </div>
  <div class="Appoinlist">
    <ul style="margin-bottom: 0px;">

      <h4> Appointment </h4>
      <% if current_user.appointments.blank? %>
      <p style="margin-bottom: 0px;">
        You have no appointments :( <i class="fa fa-thumbs-o-down"></i>
      </p>
      <% else %>
      <% current_user.appointments.each do |a| %>
      <li>Current status: <span class="aptInfofirst" id=""><%= a.stages %></span></li>
      <li>Appointment Time: <span class="aptInfo"><%= a.appointment_time.strftime('%A, %d %b %Y %l:%M %p') %></span></li>
      <li>Appointment Address: <span class="aptInfo"><%= a.address %></span></li>
      <span class="aptInfo"> <%= link_to 'Edit', edit_appointment_path(a) %></span> |
      <span class="aptInfo"><%= link_to 'Destroy', a, method: :delete, data: { confirm: 'Are you sure?' } %><span class="aptInfo">
</div>
<div class="Appoinlist">
      <h5>Items</h5>
      <% if current_user.appointments.last.stages == "Awaiting Articles" %>
        <!-- <div class="articleAlert">
            <p>ADD<br>ARTICLE</p>
        </div> -->
      <% elsif current_user.appointments.last.stages == "Awaiting Submit" %>
        <p>
          <%= button_to "BOOK", action: "appointment_booked"  %>
        </p>
      <% else %>
      <% end %>
      <span class="addArticles aptInfo"> <%= link_to 'Add Articles', new_appointment_article_path(a) %></span>
      <% a.articles.each do |art| %>
        <li><%= art.kind %> | <%= art.quantity %> </li>
        <li><span class="aptInfo"><%= link_to 'Edit', edit_article_path(art) %><span class="aptInfo"></li>
        <li><span class="aptInfo"><%= link_to 'Destroy', art, method: :delete, data: { confirm: 'Are you sure?' } %><span class="aptInfo"></li>
      <% end %>
    <% end %>
    <% end %>
    </ul>

  </div>

  <div class="Appoinlistb">

    <div>
<!-- <h3>Availabilities</h3>
<%# render '/availabilities/list_availability' %> -->

</div>


<!-- <h3>Availabilities</h3> -->
<%#render '/availabilities/listavailability' %>
<% if current_user.appointments.blank? %>
  <% if Availability.count != 0 %>
    <div class="calendar">
    <% @days.each do |day| %>
    <a style="display:block" href="availabilities/index">
    <div class="weekday">
      <p><span class="arrow">></span><br /></p>
      <h4><%= day.strftime("%A") %></h4>
      <% end %>
        </a>
    </div>
      <% end %>
        <% end %>

app/views/users/edit.html.erb
<div class= "NewuSerImgback">
  <p class="Hello">Edit Tailor</p>
  <div class="imgUser">
    <%= image_tag @user.image_url(:thumb).to_s%>
  </div>
</div>

<div class="formSpace4"></div>

<div class = "NEwuserfromA">
  <%= render 'form2' %>
</div>

<div class="canceled">
  <%= link_to content_tag(:i, nil, :class => "fa fa-chevron-left fa-3x"), dashboard_path %>
</div>

app/views/users/forgot_password.html.erb
<h1>User Password Reset in</h1>
<%=form_tag users_forgot_password_reset_path do %>
<p>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
</p>
<p>
  <%= submit_tag 'Send Email' %>
</p>
<% end %>

app/views/users/index.html.erb
<h2>User's Index Page</h2>
<p>
  Currently signed in as
  <%= current_user.first_name %>
</p>

app/views/users/new.html.erb
<div class="NewuSerImgback">
  <p class="Hello"> Welcome to TailorUp</p>
</div>

<div class = "NEwuserfromA">
<%= render 'form' %>

</div>

app/views/users/show.html.erb
<h2>Appointments</h2>
<ul>
  <% @user.appointments.each do |appointment| %>
    <li> <%= link_to user.first_name, appointment %></li>
    <% end %>
</ul>

<h3>New appointment</h3>

<%= link_to 'New appointments', new_appointment_path %>