config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

    root 'sessions#new_session_user'
    get '/availabilities' => 'availabilities#index'

  get '/new_company' => 'sessions#new_company'
  get '/new_session_tailor' => 'sessions#new_session_tailor'
  get '/new_session_user' => 'sessions#new_session_user'

  get 'tailors/edit_tailor' => 'tailors#edit_tailor'

  get 'users/forgot_password'=> 'users#forgot_password'
  post 'users/forgot_password/reset' => 'users#forgot_password_mail'

get '/availabilities/index' => 'availabilities#index'

  post 'appointments/:id' => 'appointments#status'
  post 'tailors/dashboard/data' => 'tailors#dataLog'
  post 'companies/data' => 'companies#dataLog'

  post 'dashboard/appointment_create' => 'users#appointment_booked'

  get '/dashboard' => 'users#dashboard'

  get '/tailors/dashboard'  => 'tailors#dashboard'

  post 'sessions/login_user'
  post 'sessions/login_company'
  post 'sessions/login_tailor'

  post '/tailors/:id/' => 'tailors#destroy'

  delete '/logout' => 'sessions#logout'

  resources :sessions

  resource :companies do
    resources :tailors
    resources :availabilities
  end

  resources :tailors do
    resources :appointments
    resources :availabilities
  end

  resources :users do
    resources :appointments
  end

  resources :appointments do
    resources :articles
  end

  resources :articles

  get '/session' => 'sessions#show'
  get '/login' => 'sessions#new'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_secure_password
  has_many :tailors
  has_many :availabilities, through: :tailors
  # validates_uniqueness_of :email

  before_save :format_values

  def format_values
    email.downcase!
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def show
    # @tailor = Tailor.new
    @tailor = current_company.tailors
  end

  def new
    @company = Company.new
  end

  def index
  end

  def dataLog
    @tailors = current_company.tailors
      @company = current_company
      UserMailer.send_report_company(@company).deliver
      redirect_to companies_path, flash:{notice: 'Data has been emailed'}
  end

  def create
    @company = Company.new company_params
    if @company.save
      log_in_company(@company)
      redirect_to companies_path, notice: 'Company: #{@company.name} has been created!'
    else
      redirect_to :new
    end
  end

  def edit
  end

  def update
    if company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
  @company.destroy
  end


  private

  def set_company
    # company_id is stored in the sessions, not params!!!!
    @company = Company.find(session[:company_id])
  end

  def company_params
    params.require(:company).permit(:name, :email, :password, :password_confirmation, :location)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for @company do |f| %>
<div class="formSace1"></div>
  <%= f.input :name, :placeholder => "Name", label: false %>
  <%= f.input :email, :placeholder => "Email", label: false %>
  <%= f.input :location, :placeholder => "password", label: false  %>
  <%= f.input :password, :placeholder => "pasword", label: false %>
  <%= f.input :password_confirmation, :placeholder => "password confirmation", label: false %>
  <%= f.button :submit, value="Create!"  %>
<% end %>

app/views/companies/edit.html.erb
<h1>Company Edit Page</h1>

<h1>Edit The Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %>
<div class="canceled">
  <%= link_to content_tag(:i, nil, :class => "fa fa-chevron-left fa-3x"), companies_path %>
</div>

app/views/companies/index.html.erb
<% if company_signed_in? %>
<h2>Logged In</h2>
  <li>
  <%= link_to('Logout', destroy_company_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login Company', new_company_path)  %>
  <%# link_to('signup', new_tailor_registration_path ) %>
  </li>
<% end %>

<h1>Company Index Page</h1>
<h3>Heres The Tailors</h3>


<%# link_to 'Tailors', show_company_path(:company_id)%>

app/views/companies/new.html.erb
<div class= "NewuSerImgback">
<p class="Hello">Create a Company</p>
</div>
<div class="formSpace4"></div>

<div class="NEwuserfromA">

<%= render 'form' %>
</div>

app/views/companies/show.html.erb
<div class="layer"></div>
<div class="tDashBack"></div>
<div class="darkBar"></div>
<div class="profItems">
  <div id="profNameCom">
    <p>
        CAVEAT
    </p>
  </div>
</div>
<!-- <h4>Tailors</h4> -->


<div class="dataLogSendC">
  <%= button_to "Logs", action: "dataLog"  %>
</div>
<div class="addTailor">
  <%= link_to content_tag(:i, nil, :class => "fa fa-plus-square fa-3x"), new_tailor_path %>
</div>


<div class="btnWrapper">
  <button id="showA" class="btnSelect btnZ">APPOINTMENTS</button>
  <button id="showT" class="btnSelect btnZ">TAILORS</button>
  <button id="showC" class="btnSelect btnZ">COMPLETED</button>
</div>
<table id="tableT" class="tableDash centered bordered">
  <thead>
    <tr>
      <th>TAILORS</th>
      <th>PHONE</th>
      <th>EMAIL</th>
      <th>APPOINTMENTS</th>
      <th>EDIT</th>
    </tr>
  </thead>
<tbody>
    <% @company.tailors.each do |tailor| %>
      <div class="tailAvailAptsZ">
        <tr class='compTailList'>
          <td> <%= link_to tailor.first_name, companies_tailor_path(@tailor) %></td>
          <!-- <td><%# link_to tailor.phone, :value => "#{tailor.phone}" %></td> -->
          <td> <%= tailor.phone%></td>
          <td> <%= tailor.email%></td>
          <td> <%= tailor.appointments.count %></td>
          <td>
            <%= link_to 'Availability', new_tailor_availability_path(tailor) %> |
             <%= link_to 'Destroy', tailor, method: :destroy, data: { confirm: 'Are you sure you want to delete this Tailor?' } %>
          </td>
        </tr>
      </div>
    <% end %>
  </tbody>
</table>
<table id="tableA" class="tableDash centered bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>USER</th>
      <th>ADDRESS</th>
      <th>TIME</th>
      <th>PHONE</th>
      <th>ITEMS</th>
      <th>STATUS</th>
      <th><th>
    </tr>
  </thead>
<tbody>
    <% @company.tailors.each do |tailor| %>
      <div class="tailAvailAptsZ">
        <% tailor.appointments.each do |a| %>
          <% if a.stages != "Order Complete" %>
            <tr>
              <td><%= a.id + 10000 %> </td>
              <td><%= a.user.first_name %> </td>
              <td><%= a.address %> </td>
              <td>
                <%# a.appointment_time.strftime("%b %e") %>
              <br>
                <%# a.appointment_time.strftime("%l:%M %p") %>
              </td>
              <!-- <td><%# link_to a.user.phone, :value => "#{a.user.phone}" %></td> -->
              <td><%= a.user.phone %></td>
              <td><%= a.articles.count %></td>
              <td><%= a.stages%> </td>
                <%if a.stages == "Order Complete" %>
                <%else %>
                  <td class="dataLogSend emailzz"> <%= button_to "Update", a, action: "status", data: { confirm: "Are you sure you want to update the status of #{a.tailor.first_name}'s order?" } %></td>
                <%end%>
              <% else %>
              <% end %>
            <% end %>
          </tr>
      </div>
    <% end %>
  </tbody>
</table>
<table id="tableC" class="tableDash centered bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>USER</th>
      <th>ADDRESS</th>
      <th>TIME</th>
      <th>PHONE</th>
      <th>ITEMS</th>
      <th>STATUS</th>
      <th><th>
    </tr>
  </thead>
<tbody>
    <% @company.tailors.each do |tailor| %>
      <div class="tailAvailAptsZ">
        <% tailor.appointments.each do |a| %>
          <% if a.stages == "Order Complete" %>
            <tr>
              <td><%= a.id + 10000 %> </td>
              <td><%= a.user.first_name %> </td>
              <td><%= a.address %> </td>
              <td>
                <%# a.appointment_time.strftime("%b %e") %>
              <br>
                <%# a.appointment_time.strftime("%l:%M %p") %>
              </td>
              <!-- <td><%# link_to a.user.phone, :value => "#{a.user.phone}" %></td> -->
              <td><%= a.user.phone %></td>
              <td><%= a.articles.count %></td>
              <td><%= a.stages%> </td>
            <% end %>
            <% end %>
          </tr>
      </div>
    <% end %>
  </tbody>
</table>
<div class="bottom"><p id="loggedAs">signed in as a company</p></footer></div>