config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

    root 'sessions#new_session_user'
    get '/availabilities' => 'availabilities#index'

  get '/new_company' => 'sessions#new_company'
  get '/new_session_tailor' => 'sessions#new_session_tailor'
  get '/new_session_user' => 'sessions#new_session_user'

  get 'tailors/edit_tailor' => 'tailors#edit_tailor'

  get 'users/forgot_password'=> 'users#forgot_password'
  post 'users/forgot_password/reset' => 'users#forgot_password_mail'

get '/availabilities/index' => 'availabilities#index'

  post 'appointments/:id' => 'appointments#status'
  post 'tailors/dashboard/data' => 'tailors#dataLog'
  post 'companies/data' => 'companies#dataLog'

  post 'dashboard/appointment_create' => 'users#appointment_booked'

  get '/dashboard' => 'users#dashboard'

  get '/tailors/dashboard'  => 'tailors#dashboard'

  post 'sessions/login_user'
  post 'sessions/login_company'
  post 'sessions/login_tailor'

  post '/tailors/:id/' => 'tailors#destroy'

  delete '/logout' => 'sessions#logout'

  resources :sessions

  resource :companies do
    resources :tailors
    resources :availabilities
  end

  resources :tailors do
    resources :appointments
    resources :availabilities
  end

  resources :users do
    resources :appointments
  end

  resources :appointments do
    resources :articles
  end

  resources :articles

  get '/session' => 'sessions#show'
  get '/login' => 'sessions#new'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :tailor
  has_many :availabilities
  has_many :articles

  validates :zip, format: { with: /(^\d{5}$)|(^\d{5}-\d{4}$)/, message: "- Invalid Zipcode" }
  VALID_ZIPS = %w(33146 33145 33147 33150 33149 02116 33154 33153 33156 33155 33158 33157 33160 33162 33618 33161 33166 33165 33168 33167 33170 33169 33173 33172 33175 33174 33177 33176 33179 33178 33181 33180 33183 33182 33185 33184 33187 33186 33189 33188 33190 33194 33193 33196 33195 33199 33239 33301 33304 91214 33308 33309 33106 33311 33314 33313 33317 33319 33322 33324 33323 33326 33325 33330 33331 33334 70601 34420 33844 33009 33010 33013 33012 33015 33014 85142 33016 34476 33019 33018 33020 33023 33025 33024 33027 33026 33029 33028 33031 33030 33033 33032 33035 33034 33037 33039 33055 33054 33056 33062 33064 33066 33065 33068 18447 33073 77840 33090 33092 33101 33948 33109 33112 33116 33114 33122 33126 33125 33128 33127 34744 33130 33129 33132 33131 33134 33133 33136 33135 33138 33137 33140 33139 33142 33141 33144 33143)
  validates_inclusion_of :zip, :in => VALID_ZIPS, message: "- That zipcode is not in Miami, please enter a correct zipcode."
  validates_presence_of :address
 #  validate :happened_at_is_valid_datetime
 #
 # def happened_at_is_valid_datetime
 #   errors.add(:happened_at, 'Sorry, you must choost a later time.') if ((DateTime.parse(happened_at) rescue ArgumentError) == ArgumentError)
 # end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy, :status]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = current_user.appointments.all
    # @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
      @article = Article.new
      @appointment = current_tailor
  end

  # GET /appointments/new
  def new
    if current_user
      if current_user.appointments.count <= 0
        @appointment = current_user.appointments.new
        @appointment.address = current_user.address
        @appointment.zip = current_user.zip
        @appointment.appointment_time = params[:start]
        @appointment.tailor_id = params[:tailor_id]
        # DateTime.now.strftime("%Y-%d-%m %H:%M")
          @article = Article.new
      else
        redirect_to dashboard_path
      end
    end
  end




  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = current_user.appointments.new(appointment_params)
    # availability = Availability.find(params[:availability_id])
    #  @appointment = Appointment.new(appointment_params)
    @appointment.tailor_id = params[:tailor_id]
    @appointment.stages = "Awaiting Articles"


      if @appointment.pickup_location == ""
        @appointment.pickup_location = current_user.address
      end
      @appointment.save

    respond_to do |format|
      if @appointment.save
        availability = Availability.find(params[:availability_id])
        availability.requested = true
        availability.save
        format.html { redirect_to dashboard_path, notice: 'Appointment was successfully created, add some articles.' }
        format.json { render :show, status: :created, location: @appointment }

      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def status
      if @appointment.stages == "Appointment Booked"
        @appointment.stages = "Processing Alterations"
        @appointment.save
        UserMailer.appointment_processing(@appointment).deliver
        redirect_to tailors_dashboard_path, flash:{notice: 'appointment status was changed from "Booked" to "Processing alterantions"'}
      elsif @appointment.stages == "Processing Alterations"
        @appointment.stages = "Ready for Drop Off"
        @appointment.save
        UserMailer.appointment_delivery(@appointment).deliver
        redirect_to tailors_dashboard_path, flash:{notice: 'appointment status was changed from "Processing alterantions" to "Ready for Drop Off"'}
      else @appointment.stages == "Ready for Drop Off"
        @appointment.stages = "Order Completed"
        @appointment.save
        UserMailer.appointment_complete(@appointment).deliver
        redirect_to tailors_dashboard_path, flash:{notice: 'appointment status was changed from "Ready for Drop Off" to "Order Completed"'}
      end
  end




  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.articles.destroy_all   #Removes all articles associated to Appointment
    @appointment.destroy
    respond_to do |format|
      if current_user != nil
      format.html { redirect_to dashboard_path, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }

      end


    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      # @appointment = Appointment.find(params[:id])
      @appointment = current_user.appointments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:tailor_id, :start, :stages, :address, :appointment_time, :due_time, :service, :pickup_location, :zip)
    end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <%= hidden_field_tag("tailor_id", params[:tailor_id]) %>
  <%= hidden_field_tag("availability_id", params[:availability_id]) %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>
      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# f.label :address%><br>
    <%= f.text_field :address, :placeholder => 'Address' %>
  </div>

  <div class="field">
    <span id="dropdownOther"><strong>Service:</strong><%= f.select :service, ["Next Day", "Express", "Sunday & Holiday"], {:include_blank => 'Standard'} %></span>
  </div>
  <div class="field">
    <%# f.label :pickup_location %><br>
    <%= f.text_field :pickup_location, :placeholder => 'different location?' %>
  </div>
  <div class="field">
    <%# f.label :zip %><br>
    <%= f.text_field :zip, :placeholder => 'Zipcode' %>
  </div>
  <%# raise %>
    <!-- <div class="field">    Will not be displayed because appointment_time will be set by tailor
      <%= f.label :stages %><br>
      <%= f.text_field :stages %>
    </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field hidden">  <!-- Will not be displayed because appointment_time will be set by avail -->
    <%= f.label :appointment_time %><br>
    <%= f.datetime_select :appointment_time  %>
    <%# f.datetime_select :appointment_time , :disabled => true %>

  </div>
<% end %>

app/views/appointments/_form2.html.erb
<%= form_for(@appointment) do |f| %>
  <%= hidden_field_tag("tailor_id", params[:tailor_id]) %>
  <%= hidden_field_tag("availability_id", params[:availability_id]) %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>
      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# f.label :address%><br>
    <%= f.text_field :address, :placeholder => 'Address' %>
  </div>

  <div class="field">
    <span id="dropdownOther"><strong>Service:</strong><%= f.select :service, ["Next Day", "Express", "Sunday & Holiday"], {:include_blank => 'Standard'} %></span>
  </div>
  <div class="field">
    <%# f.label :zip %><br>
    <%= f.text_field :zip, :placeholder => 'Zipcode' %>
  </div>
  <%# raise %>
    <!-- <div class="field">    Will not be displayed because appointment_time will be set by tailor
      <%= f.label :stages %><br>
      <%= f.text_field :stages %>
    </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<div class= "NewuSerImgback">
  <p class="Hello">Edit Appointment</p>
</div>

<div class="formSpace4"></div>

<div class = "NEwuserfromA">
  <%= render 'form2' %>
</div>

<div class="canceled">
  <%= link_to content_tag(:i, nil, :class => "fa fa-chevron-left fa-3x"), dashboard_path %>
</div>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Stages</th>
      <th>Address</th>
      <th>Appointment time</th>
      <th>Due time</th>
      <th>Service</th>
      <th>Pickup location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.stages %></td>
        <td><%= appointment.address %></td>
        <td><%= appointment.appointment_time %></td>
        <td><%= appointment.due_time %></td>
        <td><%= appointment.service %></td>
        <td><%= appointment.pickup_location %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure hello?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Appointment', new_appointment_path %>
<!-- <h2>Articles</h2>
<ul>
  <% @appointments.each do |appointment| %>
    <% appointment.articles.each do |art| %>
    <li><%= link_to art.kind, "" %>
    <li><%= link_to art.quantity, "" %>
      <% end %>
  <% end %>
</ul>



<%= link_to 'New Article', new_article_path %>
<br> -->

app/views/appointments/new.html.erb
<div class= "NewuSerImgback">
<p class="Hello">Appointment</p>
</div>
<div class = "NEwuserfromA">

<%= render 'form' %>
</div>
<div class="canceled">
  <%= link_to content_tag(:i, nil, :class => "fa fa-chevron-left fa-3x"), dashboard_path %>
</div>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stages:</strong>
  <%= @appointment.stages %>
</p>

<p>
  <strong>Address:</strong>
  <%= @appointment.address %>
</p>

<p>
  <strong>Appointment time:</strong>
  <%= @appointment.appointment_time %>
</p>

<p>
  <strong>Due time:</strong>
  <%= @appointment.due_time %>
</p>

<p>
  <strong>Service:</strong>
  <%= @appointment.service %>
</p>

<p>
  <strong>Pickup location:</strong>
  <%= @appointment.pickup_location %>
</p>


<p>
  <strong>Zipcode:</strong>
  <%= @appointment.zip %>
</p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Kind</th>
      <th>Quantity</th>
      <th>Other</th>
      <th>Appointment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.kind %></td>
        <td><%= article.quantity %></td>
        <td><%= article.other %></td>
        <td><%= article.appointment %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= render 'articles/form' %>

<%= link_to 'Edit Appointement', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>