config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

    root 'sessions#new_session_user'
    get '/availabilities' => 'availabilities#index'

  get '/new_company' => 'sessions#new_company'
  get '/new_session_tailor' => 'sessions#new_session_tailor'
  get '/new_session_user' => 'sessions#new_session_user'

  get 'tailors/edit_tailor' => 'tailors#edit_tailor'

  get 'users/forgot_password'=> 'users#forgot_password'
  post 'users/forgot_password/reset' => 'users#forgot_password_mail'

get '/availabilities/index' => 'availabilities#index'

  post 'appointments/:id' => 'appointments#status'
  post 'tailors/dashboard/data' => 'tailors#dataLog'
  post 'companies/data' => 'companies#dataLog'

  post 'dashboard/appointment_create' => 'users#appointment_booked'

  get '/dashboard' => 'users#dashboard'

  get '/tailors/dashboard'  => 'tailors#dashboard'

  post 'sessions/login_user'
  post 'sessions/login_company'
  post 'sessions/login_tailor'

  post '/tailors/:id/' => 'tailors#destroy'

  delete '/logout' => 'sessions#logout'

  resources :sessions

  resource :companies do
    resources :tailors
    resources :availabilities
  end

  resources :tailors do
    resources :appointments
    resources :availabilities
  end

  resources :users do
    resources :appointments
  end

  resources :appointments do
    resources :articles
  end

  resources :articles

  get '/session' => 'sessions#show'
  get '/login' => 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <title>TailorUp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>


<div class="homeButton">
    <% if current_tailor || current_company || current_user %>
        <% if current_user %>
            <%= link_to content_tag(:i, nil, :class => "fa fa-scissors fa-3x"), dashboard_path %>
        <% elsif current_company  %>
            <%= link_to content_tag(:i, nil, :class => "fa fa-scissors fa-3x"), companies_path %>
        <% elsif current_tailor %>
            <%= link_to content_tag(:i, nil, :class => "fa fa-scissors fa-3x"), tailors_dashboard_path %>
        <% else %>
        <% end %>
      <% else %>
    <%= link_to content_tag(:i, nil, :class => "fa fa-scissors fa-3x"), root_path %>
<% end %>

</div>
    <div class="userLog">
      <% if current_tailor || current_company || current_user %>
        <%= link_to 'logout', logout_path, method:"delete"%>
      <% else %>

      <%= link_to 'login', new_session_user_path%>
      <% end %>
    </div>
<%= yield %>

</body>
</html>